#ifndef __SubGUIClass__
#define __SubGUIClass__

/**
@file
Subclass of GUIClass, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"

//// end generated include

/** Implementing GUIClass */
class SubGUIClass : public GUIClass
{
	protected:
		// Handlers for GUIClass events.
		void OnExitSelected( wxCommandEvent& event );
		void OnTTTButtonClick( wxCommandEvent& event );
		void OnResetButtonClick( wxCommandEvent& event );
		void OnExitButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		SubGUIClass( wxWindow* parent );
	//// end generated class members
		void CheckWin(char player);
		void ResetGame();

	private:
		bool gameWon = false;
		bool xTurn = true;
		int turn = 1;
		wxButton* gameArray[3][3] = { {TL, TM, TR},
									  {ML, MM, MR},
									  {BL, BM, BR} };
};

#endif // __SubGUIClass__
